// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5llyuIb1tFMY5vhmX3hGMtJFaEgRDgHI',
    appId: '1:108367094195:android:a7d01dbe63f8f9155e2bc6',
    messagingSenderId: '108367094195',
    projectId: 'chat-app-cf685',
    storageBucket: 'chat-app-cf685.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCq1-8bMbCyiTZ26lrxMPwZCF6GsKaOoBs',
    appId: '1:108367094195:ios:3f46ced978746b815e2bc6',
    messagingSenderId: '108367094195',
    projectId: 'chat-app-cf685',
    storageBucket: 'chat-app-cf685.appspot.com',
    androidClientId: '108367094195-bkvnsnacu930tmioc228qujk2mb2fp8f.apps.googleusercontent.com',
    iosClientId: '108367094195-eemsumi84aam9nq76ngusjmgn28h7nh8.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCq1-8bMbCyiTZ26lrxMPwZCF6GsKaOoBs',
    appId: '1:108367094195:ios:3f46ced978746b815e2bc6',
    messagingSenderId: '108367094195',
    projectId: 'chat-app-cf685',
    storageBucket: 'chat-app-cf685.appspot.com',
    androidClientId: '108367094195-bkvnsnacu930tmioc228qujk2mb2fp8f.apps.googleusercontent.com',
    iosClientId: '108367094195-eemsumi84aam9nq76ngusjmgn28h7nh8.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
